language: go
go:
  - "1.6"

install:
  - sudo apt install snapcraft rpm
  - go get github.com/hashicorp/vault
env:
  - PATH=/snap/bin:$PATH DEBUG=1

script:
  - vault server -dev
  - go test -v -race ./gitwatch
  - go test -v -race ./server

after_success:
  - test -n "$TRAVIS_TAG" && docker login -u=southclaws -p="$DOCKER_PASSWORD"

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
